services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: pop-test
    working_dir: /app
    command: sh -c "go test ./... -v -cover"
    networks:
      - pop-test-net

networks:
  pop-test-net:
    driver: bridge
