services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: pop-test
    working_dir: /src
    command: go test ./...
    networks:
      - pop-test-net

networks:
  pop-test-net:
    driver: bridge
